version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=votingsessionmanager
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=Brazil/East
    ports:
      - 3306:3306
  main-app:
    container_name: main-app
    build: ./DevBackNTSicredi
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
