# Passando valor diferente de SIM ou NAO para o valor
POST http://localhost:8080/api/v1/vote
content-type: application/json

{
    "value" : "alguma coisa",
    "associateId" : "60099163055",
    "session" : {
        "id" : "1"
    }
}

###
#Salvando um voto sim para a sessão 2 -- Para testar a mensageria
POST http://localhost:8080/api/v1/vote
content-type: application/json

{
    "value" : "SIM",
    "associateId" : "60099163055",
    "session" : {
        "id" : 2
    }
}

###
#Votando com uma id repitida
POST http://localhost:8080/api/v1/vote
content-type: application/json

{
    "value" : "SIM",
    "associateId" : "60099163055",
    "session" : {
        "id" : 2
    }
}

###
#Votando após o final da sessão -- esperar 1 minuto
POST http://localhost:8080/api/v1/vote
content-type: application/json

{
    "value" : "SIM",
    "associateId" : "60099160355",
    "session" : {
        "id" : 2
    }
}

### Não passando a sessão
POST http://localhost:8080/api/v1/vote
content-type: application/json

{
    "value" : "SIM",
    "associateId" : "60099160355"
}

### Passando uma sessão not found
POST http://localhost:8080/api/v1/vote
content-type: application/json

{
    "value" : "SIM",
    "associateId" : "60099160355",
    "session" : {
        "id" : 40
    }
}